#!/bin/tcsh
cd ${HOME}

if ($user == "cwu") then
    set addr_user = iyaowu
else if ($user == "tungc") then
    set addr_user = ctung
else
    set addr_user = tonytung
endif

set nonomatch
foreach addrbook (.address*[^\.][^l][^u])
    set addrbookdest = `echo $addrbook | sed -e 's/\.\(.*\)/\1/'`
    if (! -l $addrbook) then
        mkdir -p .init/${addr_user}-addressbook/
        'mv' -f $addrbook .init/${addr_user}-addressbook/${addrbookdest}
    else
        'rm' -f $addrbook
    endif
end
unset nonomatch

foreach cshrc (.init/cshrc*)
    set cshrcdest = `echo $cshrc | sed -e 's/.*\/\([^\/]*\)/.\1/'`
    ln -sf $cshrc $cshrcdest
end

ln -sf .init/emacs .emacs
ln -sf .init/xstart .xstart
ln -sf .init/dvorak .dvorak
ln -sf .init/xsession .xsession
ln -sf .init/qwerty .qwerty
ln -sf .init/fvwm2rc .fvwm2rc
ln -sf .init/xmodmap .xmodmap
ln -sf .init/dvorak.keysym .dvorak.keysym
ln -sf .init/Xdefaults .Xdefaults
ln -sf .init/hushlogin .hushlogin
ln -sf .init/screenrc .screenrc

ln -sf .cshrc.aliases .aliases
ln -sf .cshrc.login .login
ln -sf .cshrc.logout .logout

ln -sf .xsession .xinitrc 

if (-d .init/${addr_user}-addressbook/) then
    foreach addrbook (.init/${addr_user}-addressbook/addr*)
        set addrbookdest = `echo $addrbook | sed -e 's/.*\/\([^\/]*\)/.\1/'`
        ln -sf $addrbook $addrbookdest
    end
endif

cd -
