#!/bin/tcsh
if ($OSTYPE == solaris) then
    xmodmap .dvorak.keysym
else if ($OSTYPE == Darwin) then
    # do nothing
else
    ~/.xmodmap ~/.dvorak | xmodmap -
endif
if (-X quartz-wm) then
    quartz-wm
else if (-X fvwm2) then
    fvwm2
else if (-X fvwm) then
    fvwm
else
    twm
endif
